#encrypted form of var, user and pass command 
#echo -n user | base64
#echo -n psw | base64
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wc3c=