apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webappdb
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env: #these are env var required for webapp to connect to db, it is preconfigured in images.
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
#Request (eg:8080/443) -> Service -> Pod (template from above deployment)
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort #NodePort is for external, ClusterIP (default) is for internal
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100 #Required for NodePort type, must be between (30000 - 32767)